services:

  http-to-mqtt-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
      - HTTP_ENDPOINTS=${HTTP_ENDPOINTS}
      - HTTP_POLL_INTERVAL_SECONDS=${HTTP_POLL_INTERVAL_SECONDS}
