services:

  http-to-mqtt-scraper:
    image: manuandru/torrevieja-http-to-mqtt-scraper:latest
    restart: unless-stopped
    environment:
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
      - HTTP_ENDPOINTS=${HTTP_ENDPOINTS}
      - HTTP_POLL_INTERVAL_SECONDS=${HTTP_POLL_INTERVAL_SECONDS}
