include:
  - path: ditto/deployment/docker/docker-compose.yml
    project_directory: ditto/deployment/docker
  - path: thing-directory/docker-compose.yaml
    project_directory: thing-directory

services:
  mqtt-broker:
    image: emqx/nanomq:latest
    ports:
      - "1883:1883"

  provisioner:
    image: manuandru/torrevieja-ditto-provisioner
    depends_on:
      nginx:
        condition: service_started
      things:
        condition: service_healthy
