name: CI & CD

on:
  push:
    paths:
      - torrevieja-sensors-integration/http-to-mqtt-scraper/**
      - torrevieja-sensors-integration/ditto-provisioner/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Test python 
      run: |
        python torrevieja-sensors-integration/http-to-mqtt-scraper/src/test/sensor_types_test.py

  build-and-push-image:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_MANUANDRU_USERNAME }}
        password: ${{ secrets.DOCKERHUB_MANUANDRU_TOKEN }}
    - name: Build and push http-to-mqtt-scraper
      uses: docker/build-push-action@v6
      with:
        push: true
        context: torrevieja-sensors-integration/http-to-mqtt-scraper
        platforms: linux/amd64,linux/arm64
        tags: manuandru/torrevieja-http-to-mqtt-scraper:latest
    - name: Build and push ditto-provisioner
      uses: docker/build-push-action@v6
      with:
        push: true
        context: torrevieja-sensors-integration/ditto-provisioner
        platforms: linux/amd64,linux/arm64
        tags: manuandru/torrevieja-ditto-provisioner:latest
