services:
  influxdb:
    image: influxdb:2
    ports:
      - "8086:8086"
    restart: unless-stopped
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxt
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG:-manuandru}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET:-torrevieja}
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxt
    volumes:
      - influxdb2-data:/var/lib/influxdb2:rw
      - influxdb2-config:/etc/influxdb2:rw

  telegraf:
    image: telegraf:1.31
    configs:
      - source: telegraf-config
        target: /etc/telegraf/telegraf.conf
    restart: unless-stopped
    environment:
      - MQTT_BROKER=${MQTT_BROKER:-tcp://mqtt-broker:1883}
      - INFLUXDB_URL=${INFLUXDB_URL:-http://influxdb:8086}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-manuandru}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-torrevieja}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-token}
    depends_on:
      - influxdb

configs:
  telegraf-config:
    file: ./telegraf.conf

secrets:
  influxdb2-admin-username:
    file: ./.env.influxdb2-admin-username
  influxdb2-admin-password:
    file: ./.env.influxdb2-admin-password
  influxt:
    file: ./.env.influxdb2-admin-token

volumes:
  influxdb2-data:
  influxdb2-config:
