services:
  influxdb:
    image: influxdb:2
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxt
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG:-manuandru}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET:-torrevieja}
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxt
    volumes:
      - influxdb2-data:/var/lib/influxdb2:rw
      - influxdb2-config:/etc/influxdb2:rw

secrets:
  influxdb2-admin-username:
    file: ./.env.influxdb2-admin-username
  influxdb2-admin-password:
    file: ./.env.influxdb2-admin-password
  influxt:
    file: ./.env.influxdb2-admin-token

volumes:
  influxdb2-data:
  influxdb2-config:
